services:
  api:
    image: my-node-api:latest
    ports:
      - "3000:3000"  # Expose API only
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
      - redis
    command: >
      sh -c "
        until nc -z mysql 3306; do
          echo 'Waiting for MySQL...';
          sleep 2;
        done;
        npm run db:migrate apply && npm start
      "

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: node_api
      MYSQL_USER: nodeapi
      MYSQL_PASSWORD: password      
    volumes:
      - mysql_data:/var/lib/mysql
    # No ports exposed

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    # No ports exposed

volumes:
  mysql_data:
  redis_data: